services:

  # Main logic; writes to DB
  processor:
    env_file:
      - .env
    build:
      context: ./processor
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python main.py

  # Connects SQLite to frontend
  api:
    build: ./api
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/aura.db
    expose:
      - "8000"

  # Streamlit Dashboard; reads from DB
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - DB_PATH=/app/data/aura.db
    depends_on:
      - processor

  # Nginx; front end
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # map config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # map html
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - api

