services:

  # Main logic; writes to DB
  processor:
    env_file:
      - .env
    build:
      context: ./processor
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/app/data
    command: python main.py

  # Streamlit Dashboard; reads from DB
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8501:8501"
    environment:
      - DB_PATH=/app/data/db.sqlite3
    depends_on:
      - processor

  # Nginx; front end
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # map config
      - ./nginx.conf:/etc/nginx/nginx/conf:ro
      # map placeholder html
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - dashboard

# Shared volume
volumes:
  sqlite_data: